In [2]:
import numpy as np

In [2]:
t=[12,4,55,45,2,34]

In [3]:
type(t)

list

In [6]:
y=np.array(t)

In [7]:
type(y)

numpy.ndarray

In [8]:
h=[[12,34,23,45],[45,67,87,12]]

In [9]:
h

[[12, 34, 23, 45], [45, 67, 87, 12]]

In [10]:
type(h)

list

In [11]:
u=np.array(h)

In [12]:
u

array([[12, 34, 23, 45],
       [45, 67, 87, 12]])

In [13]:
type(u)

numpy.ndarray

In [14]:
o=np.arange(0,10,2)

In [15]:
o

array([0, 2, 4, 6, 8])

In [16]:
type(o)

numpy.ndarray

In [17]:
np.random.rand(12)

array([0.8441555 , 0.74884781, 0.46079193, 0.78445631, 0.8613739 ,
       0.10895883, 0.31200476, 0.29019024, 0.33744844, 0.65284036,
       0.88497344, 0.77270366])

In [18]:
np.random.randn(12)

array([ 0.49370816,  0.120234  ,  0.22696634, -1.25541794,  0.28159251,
       -0.22924715, -1.5855257 ,  0.5881968 , -0.31379192, -0.69382396,
        1.13120941, -0.91239304])

In [19]:
np.random.randn(2,3)

array([[-1.08838372e-01, -5.82669257e-04,  5.44085699e-01],
       [-1.81732903e+00, -8.97350203e-01, -3.67280759e-01]])

In [23]:
np.random.randint(2,10,13)

array([9, 6, 2, 4, 4, 2, 7, 3, 7, 2, 2, 4, 6])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [35]:
y=np.arange(0,12)

In [36]:
y.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
q=np.random.randn(8)

In [51]:
q.max()

1.8522781845089378

In [52]:
q.argmax()

6

In [53]:
q

array([ 0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
       -0.60170661,  1.85227818, -0.01349722])

In [54]:
q.min()

-1.1509935774223028

In [55]:
q.argmin()

1

In [3]:
arr=np.arange(0,11)

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5]=100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr=np.arange(0,11)

In [10]:
slice_of_arr=arr[0:5]

In [11]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [12]:
slice_of_arr[:]

array([0, 1, 2, 3, 4])

In [13]:
arr_co=arr.copy()

In [14]:
arr_co

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr_2d=np.array([[12,23,34],[45,67,56],[98,34,12]])

In [16]:
arr_2d

array([[12, 23, 34],
       [45, 67, 56],
       [98, 34, 12]])

In [18]:
arr_2d.shape

(3, 3)

In [19]:
arr_2d[0]

array([12, 23, 34])

In [20]:
arr_2d[2]

array([98, 34, 12])

In [21]:
arr_2d[2][1]

34

In [22]:
arr_2d[2][0]

98

In [23]:
arr=np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
r=arr>4

In [29]:
arr[r]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[arr<4]

array([0, 1, 2, 3])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [35]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [37]:
arr/arr

<ipython-input-37-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [38]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [39]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [40]:
arr.sum()

55

In [41]:
arr.mean()

5.0

In [43]:
arr.var()

10.0

In [44]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr_2d=np.arange(0,25).reshape(5,5)

In [46]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr_2d.sum()

300

In [50]:
arr_2d.sum(0)

array([50, 55, 60, 65, 70])

In [52]:
arr_2d.sum(1)

array([ 10,  35,  60,  85, 110])